### ISSUE TITLE
[SUGGESTION] An option to keep vanilla death screen

### ISSUE THREAD

**Issue by BakinDP** [Seggan/deathview#1]
I have the mod You Were Slain, which alters death screen, but it stops working properly with DeathView installed (getting fully transparent death screen). Temporary fix is to re-enable You Were Slain via mod menu. I like to see me die in third person, but have custom death screen with stuff.

Thanks for your work!

**Comment by Seggan** [comment]
Release v1.1.0: if you have ModMenu and Cloth you can now edit some new configs, including keeping the vanilla death screen.
